### ISSUE TITLE
[BUG] Installation error due to `cornac`'s numpy dependency in setup.py

### ISSUE THREAD

**Issue by loomlike** [recommenders-team/recommenders#2001]
### Description
`cornac` package uses `numpy` from its [setup.py](https://github.com/PreferredAI/cornac/blob/master/setup.py)
This causes an error if the numpy package is not installed before cornac.

```
Collecting cornac<2,>=1.15.2 (from recommenders==1.1.1)
  Using cached cornac-1.16.0.tar.gz (8.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cc/c557w9w16wgcfbt1r4l4ygpw0000gn/T/pip-install-742rt_84/cornac_9168750d1df94eb5a47bc0b4b8009332/setup.py", line 32, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
```

### In which platform does it happen?
I'm having this issue on Mac. I'll update this issue once I test this on Linux.

### How do we replicate the issue?
pip install recommenders package.

### Expected behavior (i.e. solution)
Install recommenders without any dependency error.

**Comment by loomlike** [comment]
I confirmed I could install recommenders on Linux w/o any issues. The error happens only on non-Linux I guess. I'll close this issue since we don't officially support other OS and the resolution is also quite straightforward, that is simply manually install numpy beforehand.
