### ISSUE TITLE
Replace readthedocs with Jupyter Book

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#2016]
### Description

Documentation in readthedocs failing:
``` 
Running Sphinx v5.3.0
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
WARNING: sphinx_rtd_theme (< 0.3.0) found. It will not be available since Sphinx-6.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    args.pdb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 334, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 248, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 299, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/latest/lib/python3.7/site-packages/sphinx/theming.py", line 241, in create
    raise ThemeError(__('no theme named %r found (missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_rtd_theme' found (missing theme.conf?)

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
```

Also, we need to upgrade build.os instead of build.image on your configuration file: https://blog.readthedocs.com/use-build-os-config/

### Other Comments

It is probably better to move to Jupyter Book. See example: https://microsoft.github.io/genalog/

**Comment by miguelgfierro** [comment]
New error https://readthedocs.org/projects/microsoft-recommenders/builds/22533794/
```
Error
Problem in your project's configuration. Invalid configuration option "build.os": os not found
```

**Comment by gramhagen** [comment]
yes, @laserprec has a great example using Jupyter Book here: https://microsoft.github.io/genalog/
for this repo: https://github.com/microsoft/genalog
