### ISSUE TITLE
[BUG] Autorizaron error with new SP role 

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#2170]
### Description

```
Traceback (most recent call last):
    File "/home/runner/work/recommenders/recommenders/tests/ci/azureml_tests/submit_groupwise_azureml_pytest.py", line 137, in <module>
      client = get_client(
    File "/home/runner/work/recommenders/recommenders/tests/ci/azureml_tests/aml_utils.py", line 31, in get_client
      workspace = client.workspaces.get(workspace_name)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py", line 292, in wrapper
      return f(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
      return func(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_workspace_operations.py", line 141, in get
      return super().get(workspace_name=name, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_workspace_operations_base.py", line 87, in get
      obj = self._operation.get(resource_group, workspace_name)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
      return func(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/_restclient/v2024_07_01_preview/operations/_workspaces_operations.py", line 957, in get
      raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
  azure.core.exceptions.HttpResponseError: (AuthorizationFailed) The client 'e4d8d62a-df42-4e04-9741-d9ab05ba6ab6' with object id 'e4d8d62a-df42-4e04-9741-d9ab05ba6ab6' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/***/resourceGroups/recommenders_project_resources/providers/Microsoft.MachineLearningServices/workspaces/azureml-test-workspace' or the scope is invalid. If access was recently granted, please refresh your credentials.
  Code: AuthorizationFailed
  Message: The client 'e4d8d62a-df42-4e04-9741-d9ab05ba6ab6' with object id 'e4d8d62a-df42-4e04-9741-d9ab05ba6ab6' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/***/resourceGroups/recommenders_project_resources/providers/Microsoft.MachineLearningServices/workspaces/azureml-test-workspace' or the scope is invalid. If access was recently granted, please refresh your credentials.
  Error: Process completed with exit code 1.
```
Source: https://github.com/recommenders-team/recommenders/actions/runs/10967867314/job/30458318230

### Willingness to contribute

- [ ] Yes, I can contribute for this issue independently.
- [ ] Yes, I can contribute for this issue with guidance from Recommenders community.
- [ ] No, I cannot contribute at this time.

**Comment by miguelgfierro** [comment]
fixed in #2169
