### ISSUE TITLE
[BUG] Authentication error breaking AzureML tests

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#2193]
### Description

```
Pytest logs
  DefaultAzureCredential failed to retrieve a token from the included credentials.
  Attempted credentials:
  	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
  Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
  	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint. invalid_request
  	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
  	AzureCliCredential: Please run 'az login' to set up an account
  	AzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed
  	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
  To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
  Traceback (most recent call last):
    File "/home/runner/work/recommenders/recommenders/tests/ci/azureml_tests/post_pytest.py", line 60, in <module>
      client = get_client(
    File "/home/runner/work/recommenders/recommenders/tests/ci/azureml_tests/aml_utils.py", line 32, in get_client
      workspace = client.workspaces.get(workspace_name)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/_telemetry/activity.py", line 292, in wrapper
      return f(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
      return func(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_workspace_operations.py", line 141, in get
      return super().get(workspace_name=name, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/operations/_workspace_operations_base.py", line [88](https://github.com/recommenders-team/recommenders/actions/runs/12190267762/job/34007064737#step:3:94), in get
      obj = self._operation.get(resource_group, workspace_name)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
      return func(*args, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/ai/ml/_restclient/v2024_07_01_preview/operations/_workspaces_operations.py", line 947, in get
      pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 240, in run
      return first_node.send(pipeline_request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
      response = self.next.send(request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
      response = self.next.send(request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
      response = self.next.send(request)
    [Previous line repeated 2 more times]
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/mgmt/core/policies/_base.py", line 95, in send
      response = self.next.send(request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 204, in send
      response = self.next.send(request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 551, in send
      response = self.next.send(request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 157, in send
      self.on_request(request)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 132, in on_request
      self._request_token(*self._scopes)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 108, in _request_token
      self._token = self._get_token(*scopes, **kwargs)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 98, in _get_token
      return cast(SupportsTokenInfo, self._credential).get_token_info(*scopes, options=options)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/identity/_credentials/default.py", line 255, in get_token_info
      token_info = cast(SupportsTokenInfo, super()).get_token_info(*scopes, options=options)
    File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/azure/identity/_credentials/chained.py", line 219, in get_token_info
      raise ClientAuthenticationError(message=message)
  azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
  Attempted credentials:
  	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
  Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
  	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint. invalid_request
  	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
  	AzureCliCredential: Please run 'az login' to set up an account
  	AzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed
  	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
  To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
  Error: Process completed with exit code 1.
```

### How do we replicate the issue?

See https://github.com/recommenders-team/recommenders/actions/runs/12190267762/job/34007064737

### Willingness to contribute

- [ ] Yes, I can contribute for this issue independently.
- [ ] Yes, I can contribute for this issue with guidance from Recommenders community.
- [ ] No, I cannot contribute at this time.

**Comment by miguelgfierro** [comment]
- CPU working: https://github.com/recommenders-team/recommenders/actions/runs/12190267762
- Spark:
- GPU:
